// JavaScript Document

var logos = {
	"Atlanta Hawks":"/data/hawks.png",
	"Boston Celtics":"/data/celtics.png",
	"Brooklyn Nets":"/data/nets.png",
	"Charlotte Bobcats":"/data/bobcats.png",
	"Chicago Bulls":"/data/bulls.png",
	"Cleveland Cavaliers":"/data/cavaliers.png",
	"Dallas Mavericks":"/data/mavericks.png",
	"Denver Nuggets":"/data/nuggets.png",
	"Detroit Pistons":"/data/pistons.png",
	"Golden State Warriors":"/data/warriors.png",
	"Houston Rockets":"/data/rockets.png",
	"Indiana Pacers":"/data/pacers.png",
	"Los Angeles Clippers":"/data/clippers.png",
	"Los Angeles Lakers":"/data/lakers.png",
	"Memphis Grizzlies":"/data/grizzlies.png",
	"Miami Heat":"/data/heat.png",
	"Milwaukee Bucks":"/data/bucks.png",
	"Minnesota Timberwolves":"/data/timberwolves.png",
	"New Orleans Pelicans":"/data/pelicans.jpg",
	"New York Knicks":"/data/knicks.png",
	"Oklahoma City Thunder":"/data/thunder.png",
	"Orlando Magic":"/data/magic.png",
	"Philadelphia 76ers":"/data/76ers.png",
	"Phoenix Suns":"/data/suns.png",
	"Portland Trailblazers":"/data/trailblazers.png",
	"Sacramento Kings":"/data/kings.png",
	"San Antonio Spurs":"/data/spurs.png",
	"Toronto Raptors":"/data/raptors.png",
	"Utah Jazz":"/data/jazz.png",
	"Washington Wizards":"/data/wizards.png"
}